# Generated by Django 3.2.9 on 2021-11-28 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=30)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='None', max_length=500)),
                ('rating', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('console', models.ManyToManyField(to='gamestore.Console')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=30)),
                ('min_gpu', models.CharField(default='None', max_length=30)),
                ('min_cpu', models.CharField(default='None', max_length=30)),
                ('rec_cpu', models.CharField(default='None', max_length=30)),
                ('rec_gpu', models.CharField(default='None', max_length=30)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='None', max_length=500)),
                ('rating', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=100)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamestore.device')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=30)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='None', max_length=500)),
                ('rating', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=30)),
                ('gpu', models.CharField(default='None', max_length=30)),
                ('cpu', models.CharField(default='None', max_length=30)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='None', max_length=500)),
                ('rating', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=100)),
                ('accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamestore.item')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('console', models.ManyToManyField(to='gamestore.Console')),
                ('games', models.ManyToManyField(to='gamestore.Game')),
                ('item', models.ManyToManyField(to='gamestore.Item')),
                ('pc', models.ManyToManyField(to='gamestore.PC')),
            ],
        ),
        migrations.CreateModel(
            name='OrderThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('console', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamestore.console')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamestore.game')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamestore.item')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamestore.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_date', models.DateTimeField(verbose_name='Date and Time of purchase')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamestore.customer')),
                ('order_thing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamestore.orderthing')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='games',
            field=models.ManyToManyField(to='gamestore.Game'),
        ),
        migrations.AddField(
            model_name='customer',
            name='item',
            field=models.ManyToManyField(to='gamestore.Item'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pc',
            field=models.ManyToManyField(to='gamestore.PC'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='console',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamestore.item'),
        ),
    ]
