# Generated by Django 3.2.9 on 2021-11-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_thing',
        ),
        migrations.AddField(
            model_name='orderthing',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamestore.order'),
        ),
    ]
