# Generated by Django 3.2.9 on 2021-11-28 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pur_date',
            field=models.DateTimeField(default=datetime.time, verbose_name='Date and Time of purchase'),
        ),
    ]
