# Generated by Django 3.2.9 on 2021-11-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0004_alter_order_pur_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='console',
            field=models.ManyToManyField(null=True, to='gamestore.Console'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='games',
            field=models.ManyToManyField(null=True, to='gamestore.Game'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='item',
            field=models.ManyToManyField(null=True, to='gamestore.Item'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pc',
            field=models.ManyToManyField(null=True, to='gamestore.PC'),
        ),
    ]
