# Generated by Django 3.2.9 on 2021-12-03 05:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0010_auto_20211129_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, to='gamestore.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pur_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 5, 23, 25, 651280, tzinfo=utc), verbose_name='Date and Time of purchase'),
        ),
    ]
