# Generated by Django 3.2.9 on 2021-12-06 23:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamestore', '0013_auto_20211203_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='pur_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 23, 2, 51, 777485, tzinfo=utc), verbose_name='Date and Time of purchase'),
        ),
    ]
