# Generated by Django 3.2.9 on 2021-12-06 23:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0014_auto_20211207_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pur_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 23, 25, 1, 435670, tzinfo=utc), verbose_name='Date and Time of purchase'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='console',
            field=models.ManyToManyField(blank=True, null=True, to='gamestore.Console'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, to='gamestore.Game'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='gamestore.Item'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pc',
            field=models.ManyToManyField(blank=True, null=True, to='gamestore.PC'),
        ),
    ]
