# Generated by Django 3.2.9 on 2021-12-14 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0015_auto_20211207_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='console',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='games',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='item',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pc',
        ),
        migrations.AlterField(
            model_name='order',
            name='pur_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 7, 24, 1, 641477, tzinfo=utc), verbose_name='Date and Time of purchase'),
        ),
    ]
